name: Deploy Infrastructure and App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check AWS Credentials
        run: |
          echo "AWS Access Key: $AWS_ACCESS_KEY_ID"
          echo "AWS Secret Key: $AWS_SECRET_ACCESS_KEY"


        # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 3: Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      # Step 4: Plan Terraform
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform

      # Step 5: Apply Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform

       # Step 6: Deploy App on EC2
      - name: Deploy App on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ./key.pem ec2-user@$EC2_PUBLIC_IP << 'EOF'
          # Copy docker-compose.yaml to EC2
          cat << 'COMPOSE' > docker-compose.yaml
          version: '3.8'
          services:
            app:
              image: privatebin/s3
              ports:
                - "80:80"
              environment:
                - S3_BUCKET=${S3_BUCKET}
                - S3_REGION=${AWS_REGION}
          COMPOSE

          # Run docker-compose
          docker-compose up -d
          EOF
        env:
          S3_BUCKET: "var.s3_bucket_name"  # Or whatever you set here
        shell: bash

      # Step 7: Upload the Logs (optional)
      - name: Upload Logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: terraform-logs
          path: terraform.log
