name: Deploy Infrastructure and App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

        # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 3: Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: thgbin/terraform

      # Step 4: Plan Terraform
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: thgbin/terraform

      # Step 5: Apply Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: thgbin/terraform

      # Step 6: Fetch EC2 Public IP
      - name: Fetch EC2 Public IP
        id: ec2_ip
        run: |
          EC2_PUBLIC_IP=$(terraform output -raw ec2_public_ip)
          echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV
        working-directory: thgbin/terraform

      # Step 7: Fetch S3 Bucket Name
      - name: Fetch S3 Bucket Name
        id: s3_bucket
        run: |
          S3_BUCKET=$(terraform output -raw s3_bucket_name)
          echo "S3_BUCKET=$S3_BUCKET" >> $GITHUB_ENV

      # Step 8: SSH into EC2 and Deploy Docker Compose
      - name: Deploy App on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ./key.pem ubuntu@$EC2_PUBLIC_IP << 'EOF'
          # Install Docker if not already installed
          sudo apt update
          sudo apt install -y docker.io docker-compose

          # Copy docker-compose.yaml to EC2
          cat << 'COMPOSE' > docker-compose.yaml
          version: '3.8'
          services:
            app:
              image: privatebin/s3
              ports:
                - "80:80"
              environment:
                - S3_BUCKET=${S3_BUCKET}
                - S3_REGION=${AWS_REGION}
          COMPOSE

          # Run docker-compose
          docker-compose up -d
          EOF
        env:
          S3_BUCKET: ${{ env.S3_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        shell: bash

      # Step 9: Upload the Logs (optional)
      - name: Upload Logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: terraform-logs
          path: terraform.log
